spring:
  application:
    name: version1
  datasource:
    url: jdbc:postgresql://localhost:5432/LearnPath
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite